name: 'Fume Deployment'
description: 'Deploy fume environments with Github Actions'
author: 'Kevin Olson <acidjazz@gmail.com>'
branding:
  icon: 'cloud-lightning'
  color: 'blue'
inputs:
  environment:
    description: 'Environment to deploy to'
    required: true
  token:
    description: 'Fume Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Update Yarn
      run: yarn set version stable
      shell: bash
    - name: Install Fume
      run: yarn global add fume-cli
      shell: bash
    - name: Grab and store yarn's global bin
      id: yarn-bin
      run: echo "::set-output name=dir::$(yarn global bin)"
      shell: bash
    - name: Run a yarn install
      run: yarn install
      shell: bash
    - name: Deploy with Fume
      run: ${{ steps.yarn-bin.outputs.dir }}/fume deploy ${{ inputs.environment }}
      env:
        FUME_TOKEN: ${{ inputs.token }}
      shell: bash
